<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 public/models/cd.glb
Author: beewee (https://sketchfab.com/beewee)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-cd-a4bc4accb20b43ffa728a7a85b7dfed7
Title: Lowpoly CD
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import type { Group, Object3DEventMap } from 'three';

	let {
		fallback,
		error,
		ref = $bindable(),
		...props
	}: typeof T.Group & {
		fallback?: Snippet<[]>;
		error?: Snippet<[{ error: unknown }]>;
		ref?: Group<Object3DEventMap>;
	} = $props();

	const gltf = useGltf('/models/cd.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await $gltf}
		{@render fallback?.()}
	{:then gltf}
		{#if gltf}
			<T.Mesh
				wireframe
				geometry={gltf?.nodes.Object_2.geometry}
				material={gltf?.materials.lambert2SG}
				rotation.y={-Math.PI / 2}
			/>
		{/if}
	{:catch err}
		{@render error?.({ error: err })}
	{/await}
</T.Group>
